### ISSUE TITLE
Full disclosure

### ISSUE THREAD

**Issue by jjeffhendryx** [auto-joe/rPi-xmrig-gcc7.3.0#1]
what did you tweak in the flags.cmake file

**Comment by jjeffhendryx** [comment]
Ahh, you specified the gcc version correctly as per the one you implemented.

**Comment by auto-joe** [comment]
Hi @jjeffhendryx 
Sorry for the slow response. For transparency's sake, I merely changed this line and the line under it (lines 25 & 26): https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L25

Nothing fancy or nefarious :)
