### ISSUE TITLE
installation (?) problem

### ISSUE THREAD

**Issue by reVox96** [auto-joe/rPi-xmrig-gcc7.3.0#3]
Heya, i have a problem with starting miner:
i successfully cloned git repo, but when i want to start it (./xmrig -o xmr.pool.minergate.com:45700 -u robik123.345@gmail.com -p x -k) i get this error: 
"./xmrig: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory".
This happens on rPi 3 & rPi 0w. 
Maybe should i install this library? How?
Thanks for help.

**Comment by auto-joe** [comment]
Hi, please install with:
`sudo apt-get install libmicrohttpd-dev`
Sorry that is not clear in the README.

**Comment by auto-joe** [comment]
Just to note, XMRig will not work on a pi zero, since that is ARMv6 architecture
