### ISSUE TITLE
Static Binary

### ISSUE THREAD

**Issue by DarrenRainey** [auto-joe/rPi-xmrig-gcc7.3.0#4]
Hello can you make a static binary or a guide on how you compiled your binary as I plan on deploying this on my pi cluster.

**Comment by auto-joe** [comment]
Happy to help! I’m not sure I totally understand what you’d like me to do differently to make that, could you clarify?

**Comment by DarrenRainey** [comment]
Ideally I would like a static binary that can be transferred to other devices without having to install any extra tools I have noticed that by default your binary is a dynamically shared one meaning it won't work unless the required library's are installed where as a static binary contains all of the dependencies in one package.

However I no longer require this binary as I have found a fork of cpuminer-multi that does the job and I was able to statically compile that.

Thanks anyway.
