### ISSUE TITLE
can you update this for the new POW

### ISSUE THREAD

**Issue by 0xman** [auto-joe/rPi-xmrig-gcc7.3.0#5]
Hey man can you update the miner for the new PoW?

**Comment by jp5282** [comment]
Ditto. The current binary is working great for me on crypto-light. Thanks for publishing this. With the Monero hard fork though, cryptonight is useless until update. I know xmrig has updated for new PoW. Can you update to v2.8+?

EDIT: hit submit too fast

**Comment by auto-joe** [comment]
Hi,

Yes, I will see to that this week. I apologize for being so quiet on this project, I hadn't realized so many people were interested in it (but I think that's awesome!). 

Thank you for the support, I will update this issue when I've built and released a new version

**Comment by auto-joe** [comment]
I just pushed the new binary for 2.8.3 tonight. I gave it a quick test locally and it seems to be working. Please let me know if there are any issues.

Thanks for your patience and support!
