### ISSUE TITLE
How to mine cn-heavy/xhv ?

### ISSUE THREAD

**Issue by furiousteam** [auto-joe/rPi-xmrig-gcc7.3.0#6]
Thank you for this great miner

I'm trying to mine cn-heavy/xhv. It was added in [XMRig v2.6.3](https://github.com/xmrig/xmrig/releases/tag/v2.6.3)

But i'm not able to use the [xhv variant](
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants)

Any tips please ? 😎

**Comment by auto-joe** [comment]
I have not personally tried this algo variant, but will take some time this week to see if I can get it working and update you here.

Thank you for your support!

**Comment by furiousteam** [comment]
thank you for your response 👍😎

**Comment by auto-joe** [comment]
It seems the proper flag to use is `-a cryptonight-heavy`. This _should_ be supported in the current version, but haven't tested it. I'm currently working on 2.8.3. I created a haven wallet address and it seems to be working for me:
![pic](https://user-images.githubusercontent.com/36910425/48692298-5b9f9780-eb8a-11e8-9ce8-c75e850621d9.png)

**Comment by furiousteam** [comment]
Thank you 👍  This is amazing :) It works ! I used the latest version.
